from main import create_app
import os

app = create_app()

app.app_context().push()

from main import db
if __name__ == '__main__':
    db.create_all()
    app.run(debug=True, port=os.getenv('PORT'))


# TOKEN
# USER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNzAyNDQ0NCwianRpIjoiZTQ5OGZjM2MtN2U3NC00NWQ2LTg5MGUtZjU5MWNjMzJjNDUwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MTEwLCJuYmYiOjE3MTcwMjQ0NDQsImNzcmYiOiJiZTljNDRiYi0xYzc0LTRiN2EtYmE3OC1iYzg2ZWRkYTVmOTUiLCJyb2wiOiJ1c2VyIiwiaWQiOjExMCwiZW1haWwiOiJ1c2VyIn0.c21ku-m_Ds1JfR1jS4OEcNFk8sRFb0FTIuwahcgS6SA
# ADMIN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxNjkxOTczMCwianRpIjoiNGMyYjg1ZDYtYzAyNi00YWNkLWIyYjMtMjcwNzI5ODBjMzQ2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MTAxLCJuYmYiOjE3MTY5MTk3MzAsImNzcmYiOiI1YzIxNzc1Ni1hZmNlLTQwYTktYjhlNC00NmM5NjY1NDE0YzIiLCJyb2wiOiJhZG1pbiIsImlkIjoxMDEsImVtYWlsIjoibWFndWlAZXhhbXBsZS5jb20ifQ.Ao9SqjQsjx3vDmVKgNek6FtNbAdKplNtVV9gSD_tmnE