from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .valoraciones import Valoraciones as ValoracionesResources
from .comentario import Comentario as ComentarioResources
from .comentario import Comentarios as ComentariosResources
from .configuracion import Configuraciones as ConfiguracionesResources
from .libros import Libros as LibrosResources
from .libros import Libro as LibroResources
from .login import LogIn as LogInResources
from .notificacion import Notificaciones as NotificacionesResources
from .prestamo import Prestamo as PrestamoResource
from .prestamo import Prestamos as PrestamosResource
from .sing_in import SignIn as SignInResources