from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .valoraciones import Valoraciones as ValoracionesResources
from .valoraciones import Valoracion as ValoracionResources
from .comentario import Comentario as ComentarioResources
from .comentario import Comentarios as ComentariosResources
from .configuracion import Configuraciones as ConfiguracionesResources
from .libros import Libros as LibrosResources
from .libros import Libro as LibroResources
from .login import LogIn as LogInResources
from .notificacion import Notificaciones as NotificacionesResources
from .prestamo import Prestamo as PrestamoResource
from .prestamo import Prestamos as PrestamosResource
from .signin import SignIn as SignInResources
from .autor import Autor as AutorResource
from .autor import Autores as AutoresResource