from .usuario import Usuarios as UsuarioModel
from .libro import Libros as LibroModel
from .notificacion import Notificaciones as NotificacionModel
from .configuracion import Configuraciones as ConfiguracionModel
from .prestamo import Prestamos as PrestamoModel
from .autor import Autores as AutorModel
from .opinion import Opiniones as OpinionModel
from .libro import autor_libro as autor_libroModel
from .stock import Stock as StockModel
